version: '3'
services:
  nextcloudplus:
    image: ownyourbits/nextcloudplus-armhf
    command: "${IP}"
    ports:
     - "80:80"
     - "443:443"
     - "4443:4443"
    volumes:
     - ncdata:/data

volumes:
  ncdata:
