version: '3'
services:
  nextcloudplus-dev:
    image: ownyourbits/nextcloudplus-x86
    command: "${IP}"
    ports:
     - "80:80"
     - "443:443"
     - "4443:4443"
    volumes:
     - ./ncp-web:/var/www/ncp-web
     - ./etc:/usr/local/etc
     - ./changelog.md:/changelog.md
     - ncdata:/data

volumes:
  ncdata:
